from enum import Enum

class event_type(Enum):
    DELETE_NOMENCLATURE = 1
    CHANGE_NOMENCLATURE = 2
    CHANGE_NOMENCLATURE_FROM_RECIPE = 3
    CHANGE_NOMENCLATURE_FROM_TRANSACTION = 4
    CHANGE_NOMENCLATURE_FROM_TURNOVER = 5
    CHANGE_RANGE = 6
    CHANGE_BLOCK_PERIOD = 7