swagger: '2.0'
info:
  description: Набор сервисов для работы с системой учета /ООО Ромашка/
  version: "1.0.0"
  title: RestAPI
consumes:
  - application/json
  - application/xml
  - application/text
produces:
  - application/json
  - application/xml
  - application/text
basePath: "/api"

paths:
  /reports/formats:
    get:
      summary: Получить список форматов
      operationId: main.formats
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка

  /reports/{category}:
    get:
      summary: Получить отчёт по заданным параметрам
      operationId: main.get_report
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере

        400:
          description: Ошибка ввода данных
        default:
          description: Неизвестная ошибка
    parameters:
    - name: category
      in: path
      description: Наименование категории данных (nomenclature, nomenclature_group, range, recipe)
      required: true
      type: string

  /filter/{domain_type}:
    post:
      summary: Фильтрация данных по указанной модели
      operationId: main.filter_data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: domain_type
          in: path
          required: true
          type: string
          description: Тип модели для фильтрации (range, group, nomenclature, recipes)
        - in: body
          name: filter_dto
          description: DTO модель для фильтрации данных
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              unique_code:
                type: string
              type:
                type: integer
      responses:
        200:
          description: Успешная фильтрация данных
          schema:
            type: array
            items:
              type: object
        400:
          description: Неверные параметры фильтрации или тип данных
        404:
          description: Данные не найдены
        500:
          description: Ошибка на сервере